using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Bielu.AspNetCore.AsyncApi.SourceGenerators
{
    [Generator]
    public class AsyncApiMetadataGenerator : IIncrementalGenerator
    {
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => (s is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0) || (s is InterfaceDeclarationSyntax ids && ids.AttributeLists.Count > 0),
                transform: (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(t => t != null)
            .Select((t, _) => t!);

        var compilation = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilation, (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static TypeDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var typeDeclaration = (TypeDeclarationSyntax)context.Node;
        foreach (var attributeList in typeDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var attributeSymbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
                if (attributeSymbol == null) continue;

                var attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                var fullName = attributeContainingTypeSymbol.ToDisplayString();

                if (fullName == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.AsyncApiAttribute")
                {
                    return typeDeclaration;
                }
            }
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<TypeDeclarationSyntax> types, SourceProductionContext context)
    {
        if (types.IsDefaultOrEmpty) return;

        var distinctTypes = types.Distinct();
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using Bielu.AspNetCore.AsyncApi.Attributes.Attributes;");
        sb.AppendLine("using Bielu.AspNetCore.AsyncApi.Models.Metadata;");
        sb.AppendLine("using Bielu.AspNetCore.AsyncApi.Services;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("namespace Bielu.AspNetCore.AsyncApi.Generated");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine("public sealed class GeneratedAsyncApiMetadataProvider : IAsyncApiMetadataProvider");
        sb.AppendLine("{");
        sb.AppendLine("    public IEnumerable<AsyncApiTypeMetadata> GetMetadata(string documentName)");
        sb.AppendLine("    {");

        foreach (var typeDecl in distinctTypes)
        {
            var model = compilation.GetSemanticModel(typeDecl.SyntaxTree);
            var symbol = model.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
            if (symbol == null) continue;

            var asyncApiAttr = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.AsyncApiAttribute");
            if (asyncApiAttr == null) continue;

            var docName = asyncApiAttr.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "";
            
            sb.AppendLine($"        if (string.Equals(documentName, \"{docName}\", StringComparison.OrdinalIgnoreCase) || \"{docName}\" == \"\")");
            sb.AppendLine("        {");
            sb.AppendLine($"            yield return new AsyncApiTypeMetadata(");
            sb.AppendLine($"                typeof({symbol.ToDisplayString()}),");
            sb.AppendLine($"                new AsyncApiAttribute(\"{docName}\"),");
            sb.AppendLine("                new List<AsyncApiMemberMetadata>");
            sb.AppendLine("                {");

            var members = new List<ISymbol> { symbol };
            members.AddRange(symbol.GetMembers().Where(m => m is IMethodSymbol || m is IPropertySymbol));

            foreach (var member in members)
            {
                var attrs = member.GetAttributes();
                var channelAttr = attrs.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.ChannelAttribute");
                if (channelAttr == null && member is IMethodSymbol)
                {
                     channelAttr = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.ChannelAttribute");
                }

                if (channelAttr == null && !SymbolEqualityComparer.Default.Equals(member, symbol)) continue;

                sb.AppendLine("                    new AsyncApiMemberMetadata(");
                if (SymbolEqualityComparer.Default.Equals(member, symbol))
                    sb.AppendLine($"                        typeof({symbol.ToDisplayString()}),");
                else
                    sb.AppendLine($"                        typeof({symbol.ToDisplayString()}).GetMember(\"{member.Name}\", BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)[0],");
                
                if (channelAttr != null)
                {
                    var name = channelAttr.ConstructorArguments[0].Value;
                    var description = channelAttr.NamedArguments.FirstOrDefault(x => x.Key == "Description").Value.Value as string;
                    var descValue = description != null ? $"\"{description}\"" : "null";
                    var bindingsRef = channelAttr.NamedArguments.FirstOrDefault(x => x.Key == "BindingsRef").Value.Value as string;
                    var bindingsValue = bindingsRef != null ? $"\"{bindingsRef}\"" : "null";
                    sb.AppendLine($"                        new ChannelAttribute(\"{name}\") {{ Description = {descValue}, BindingsRef = {bindingsValue} }},");
                }
                else
                {
                    sb.AppendLine("                        null,");
                }

                sb.AppendLine("                        new List<ChannelParameterAttribute>");
                sb.AppendLine("                        {");
                foreach (var attr in attrs.Where(a => a.AttributeClass?.ToDisplayString() == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.ChannelParameterAttribute"))
                {
                    var name = attr.ConstructorArguments[0].Value;
                    var type = attr.ConstructorArguments[1].Value as ITypeSymbol;
                    var description = attr.NamedArguments.FirstOrDefault(x => x.Key == "Description").Value.Value as string;
                    var descValue = description != null ? $"\"{description}\"" : "null";
                    var location = attr.NamedArguments.FirstOrDefault(x => x.Key == "Location").Value.Value as string;
                    var locationValue = location != null ? $"\"{location}\"" : "null";
                    sb.AppendLine($"                            new ChannelParameterAttribute(\"{name}\", typeof({type?.ToDisplayString()})) {{ Description = {descValue}, Location = {locationValue} }},");
                }
                sb.AppendLine("                        },");

                sb.AppendLine("                        new List<MessageAttribute>");
                sb.AppendLine("                        {");
                foreach (var attr in attrs.Where(a => a.AttributeClass?.ToDisplayString() == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.MessageAttribute"))
                {
                    var payloadType = attr.ConstructorArguments[0].Value as ITypeSymbol;
                    var name = attr.NamedArguments.FirstOrDefault(x => x.Key == "Name").Value.Value as string;
                    var nameValue = name != null ? $"\"{name}\"" : "null";
                    var title = attr.NamedArguments.FirstOrDefault(x => x.Key == "Title").Value.Value as string;
                    var titleValue = title != null ? $"\"{title}\"" : "null";
                    var summary = attr.NamedArguments.FirstOrDefault(x => x.Key == "Summary").Value.Value as string;
                    var summaryValue = summary != null ? $"\"{summary}\"" : "null";
                    var description = attr.NamedArguments.FirstOrDefault(x => x.Key == "Description").Value.Value as string;
                    var descValue = description != null ? $"\"{description}\"" : "null";
                    var bindingsRef = attr.NamedArguments.FirstOrDefault(x => x.Key == "BindingsRef").Value.Value as string;
                    var bindingsValue = bindingsRef != null ? $"\"{bindingsRef}\"" : "null";
                    var messageId = attr.NamedArguments.FirstOrDefault(x => x.Key == "MessageId").Value.Value as string;
                    var messageIdValue = messageId != null ? $"\"{messageId}\"" : "null";
                    sb.AppendLine($"                            new MessageAttribute(typeof({payloadType?.ToDisplayString()})) {{ Name = {nameValue}, Title = {titleValue}, Summary = {summaryValue}, Description = {descValue}, BindingsRef = {bindingsValue}, MessageId = {messageIdValue} }},");
                }
                sb.AppendLine("                        },");

                sb.AppendLine("                        new List<OperationAttribute>");
                sb.AppendLine("                        {");
                foreach (var attr in attrs.Where(a => a.AttributeClass?.ToDisplayString().EndsWith("OperationAttribute") == true))
                {
                    var attrName = attr.AttributeClass?.ToDisplayString();
                    var opType = attr.NamedArguments.FirstOrDefault(x => x.Key == "OperationType").Value.Value;
                    // Note: OperationAttribute is abstract, so we check for Publish/Subscribe or the base if used (though base is abstract)
                    string ctor;
                    if (attrName == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.PublishOperationAttribute")
                    {
                        var payloadType = attr.ConstructorArguments.FirstOrDefault().Value as ITypeSymbol;
                        ctor = $"new PublishOperationAttribute(typeof({payloadType?.ToDisplayString()}))";
                    }
                    else if (attrName == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.SubscribeOperationAttribute")
                    {
                        var payloadType = attr.ConstructorArguments.FirstOrDefault().Value as ITypeSymbol;
                        ctor = $"new SubscribeOperationAttribute(typeof({payloadType?.ToDisplayString()}))";
                    }
                    else
                    {
                        // Generic OperationAttribute handling if it was somehow used
                        ctor = "null"; // Should not happen as it's abstract
                        continue;
                    }

                    var opId = attr.NamedArguments.FirstOrDefault(x => x.Key == "OperationId").Value.Value as string;
                    var opIdValue = opId != null ? $"\"{opId}\"" : "null";
                    var title = attr.NamedArguments.FirstOrDefault(x => x.Key == "Title").Value.Value as string;
                    var titleValue = title != null ? $"\"{title}\"" : "null";
                    var summary = attr.NamedArguments.FirstOrDefault(x => x.Key == "Summary").Value.Value as string;
                    var summaryValue = summary != null ? $"\"{summary}\"" : "null";
                    var description = attr.NamedArguments.FirstOrDefault(x => x.Key == "Description").Value.Value as string;
                    var descValue = description != null ? $"\"{description}\"" : "null";
                    var bindingsRef = attr.NamedArguments.FirstOrDefault(x => x.Key == "BindingsRef").Value.Value as string;
                    var bindingsValue = bindingsRef != null ? $"\"{bindingsRef}\"" : "null";
                    
                    sb.AppendLine($"                            {ctor} {{ OperationId = {opIdValue}, Title = {titleValue}, Summary = {summaryValue}, Description = {descValue}, BindingsRef = {bindingsValue} }},");
                }
                sb.AppendLine("                        },");

                sb.AppendLine("                        new List<MessageExampleAttribute>");
                sb.AppendLine("                        {");
                foreach (var attr in attrs.Where(a => a.AttributeClass?.ToDisplayString() == "Bielu.AspNetCore.AsyncApi.Attributes.Attributes.MessageExampleAttribute"))
                {
                    var name = attr.NamedArguments.FirstOrDefault(x => x.Key == "Name").Value.Value as string;
                    var nameValue = name != null ? $"\"{name}\"" : "null";
                    var summary = attr.NamedArguments.FirstOrDefault(x => x.Key == "Summary").Value.Value as string;
                    var summaryValue = summary != null ? $"\"{summary}\"" : "null";
                    var json = attr.NamedArguments.FirstOrDefault(x => x.Key == "Json").Value.Value as string;
                    // Escape json string if not null
                    var jsonValue = json != null ? $"@\"{json.Replace("\"", "\"\"")}\"" : "null";
                    var providerType = attr.NamedArguments.FirstOrDefault(x => x.Key == "ProviderType").Value.Value as ITypeSymbol;
                    var providerValue = providerType != null ? $"typeof({providerType.ToDisplayString()})" : "null";

                    sb.AppendLine($"                            new MessageExampleAttribute {{ Name = {nameValue}, Summary = {summaryValue}, Json = {jsonValue}, ProviderType = {providerValue} }},");
                }
                sb.AppendLine("                        }");
                sb.AppendLine("                    ),");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            );");
            sb.AppendLine("        }");
        }

        sb.AppendLine("}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine();
        sb.AppendLine("using Bielu.AspNetCore.AsyncApi.Generated;");
        sb.AppendLine("using Bielu.AspNetCore.AsyncApi.Services;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedAsyncApiMetadataExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddAsyncApiGeneratedMetadata(this IServiceCollection services, string documentName)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.Replace(ServiceDescriptor.KeyedSingleton<IAsyncApiMetadataProvider, GeneratedAsyncApiMetadataProvider>(documentName));");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("}");

        context.AddSource("GeneratedAsyncApiMetadataProvider.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
}
