<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Bielu.AspNetCore.AsyncApi.Attributes\Bielu.AspNetCore.AsyncApi.Attributes.csproj" />
    <ProjectReference Include="..\..\Bielu.AspNetCore.AsyncApi\Bielu.AspNetCore.AsyncApi.csproj" />
    <ProjectReference Include="..\..\Bielu.AspNetCore.AsyncApi.Extensions.Protocols.SignalR\Bielu.AspNetCore.AsyncApi.Extensions.Protocols.SignalR.csproj" />
    <ProjectReference Include="..\..\Bielu.AspNetCore.AsyncApi.Scalar.SignalR\Bielu.AspNetCore.AsyncApi.Scalar.SignalR.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
