<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Bielu.AspNetCore.AsyncApi.Tests.LibraryChannels</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bielu.AspNetCore.AsyncApi.Attributes\Bielu.AspNetCore.AsyncApi.Attributes.csproj" />
    </ItemGroup>

</Project>
